language: php
php:
    - '5.5'
    - '5.6'
    - '7.0'

before_install:
    - composer self-update --no-interaction

install:
    - composer install --prefer-dist --no-interaction

script:
    - bin/phpspec run
